from setuptools import setup
from Cython.Build import cythonize

setup(
    name='particle_swarm_optimizer',
    version='0.0',
    packages=['Lib', 'Lib.site-packages', 'Lib.site-packages.PIL', 'Lib.site-packages.pip',
              'Lib.site-packages.pip._vendor', 'Lib.site-packages.pip._vendor.idna',
              'Lib.site-packages.pip._vendor.tomli', 'Lib.site-packages.pip._vendor.pep517',
              'Lib.site-packages.pip._vendor.pep517.in_process', 'Lib.site-packages.pip._vendor.certifi',
              'Lib.site-packages.pip._vendor.chardet', 'Lib.site-packages.pip._vendor.chardet.cli',
              'Lib.site-packages.pip._vendor.chardet.metadata', 'Lib.site-packages.pip._vendor.distlib',
              'Lib.site-packages.pip._vendor.distlib._backport', 'Lib.site-packages.pip._vendor.msgpack',
              'Lib.site-packages.pip._vendor.urllib3', 'Lib.site-packages.pip._vendor.urllib3.util',
              'Lib.site-packages.pip._vendor.urllib3.contrib',
              'Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'Lib.site-packages.pip._vendor.urllib3.packages',
              'Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'Lib.site-packages.pip._vendor.colorama', 'Lib.site-packages.pip._vendor.html5lib',
              'Lib.site-packages.pip._vendor.html5lib._trie', 'Lib.site-packages.pip._vendor.html5lib.filters',
              'Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'Lib.site-packages.pip._vendor.html5lib.treebuilders', 'Lib.site-packages.pip._vendor.progress',
              'Lib.site-packages.pip._vendor.requests', 'Lib.site-packages.pip._vendor.tenacity',
              'Lib.site-packages.pip._vendor.packaging', 'Lib.site-packages.pip._vendor.resolvelib',
              'Lib.site-packages.pip._vendor.resolvelib.compat', 'Lib.site-packages.pip._vendor.cachecontrol',
              'Lib.site-packages.pip._vendor.cachecontrol.caches', 'Lib.site-packages.pip._vendor.platformdirs',
              'Lib.site-packages.pip._vendor.webencodings', 'Lib.site-packages.pip._vendor.pkg_resources',
              'Lib.site-packages.pip._internal', 'Lib.site-packages.pip._internal.cli',
              'Lib.site-packages.pip._internal.req', 'Lib.site-packages.pip._internal.vcs',
              'Lib.site-packages.pip._internal.index', 'Lib.site-packages.pip._internal.utils',
              'Lib.site-packages.pip._internal.models', 'Lib.site-packages.pip._internal.network',
              'Lib.site-packages.pip._internal.commands', 'Lib.site-packages.pip._internal.metadata',
              'Lib.site-packages.pip._internal.locations', 'Lib.site-packages.pip._internal.operations',
              'Lib.site-packages.pip._internal.operations.build', 'Lib.site-packages.pip._internal.operations.install',
              'Lib.site-packages.pip._internal.resolution', 'Lib.site-packages.pip._internal.resolution.legacy',
              'Lib.site-packages.pip._internal.resolution.resolvelib', 'Lib.site-packages.pip._internal.distributions',
              'Lib.site-packages.numpy', 'Lib.site-packages.numpy.ma', 'Lib.site-packages.numpy.ma.tests',
              'Lib.site-packages.numpy.doc', 'Lib.site-packages.numpy.fft', 'Lib.site-packages.numpy.fft.tests',
              'Lib.site-packages.numpy.lib', 'Lib.site-packages.numpy.lib.tests', 'Lib.site-packages.numpy.core',
              'Lib.site-packages.numpy.core.tests', 'Lib.site-packages.numpy.f2py',
              'Lib.site-packages.numpy.f2py.tests', 'Lib.site-packages.numpy.tests', 'Lib.site-packages.numpy.compat',
              'Lib.site-packages.numpy.compat.tests', 'Lib.site-packages.numpy.linalg',
              'Lib.site-packages.numpy.linalg.tests', 'Lib.site-packages.numpy.random',
              'Lib.site-packages.numpy.random.tests', 'Lib.site-packages.numpy.random.tests.data',
              'Lib.site-packages.numpy.typing', 'Lib.site-packages.numpy.typing.tests',
              'Lib.site-packages.numpy._typing', 'Lib.site-packages.numpy.testing',
              'Lib.site-packages.numpy.testing.tests', 'Lib.site-packages.numpy.testing._private',
              'Lib.site-packages.numpy.array_api', 'Lib.site-packages.numpy.array_api.tests',
              'Lib.site-packages.numpy.distutils', 'Lib.site-packages.numpy.distutils.tests',
              'Lib.site-packages.numpy.distutils.command', 'Lib.site-packages.numpy.distutils.fcompiler',
              'Lib.site-packages.numpy.matrixlib', 'Lib.site-packages.numpy.matrixlib.tests',
              'Lib.site-packages.numpy.polynomial', 'Lib.site-packages.numpy.polynomial.tests',
              'Lib.site-packages.numpy._pyinstaller', 'Lib.site-packages.wheel', 'Lib.site-packages.wheel.cli',
              'Lib.site-packages.wheel.vendored', 'Lib.site-packages.wheel.vendored.packaging',
              'Lib.site-packages.dateutil', 'Lib.site-packages.dateutil.tz', 'Lib.site-packages.dateutil.parser',
              'Lib.site-packages.dateutil.zoneinfo', 'Lib.site-packages.contourpy', 'Lib.site-packages.contourpy.util',
              'Lib.site-packages.fontTools', 'Lib.site-packages.fontTools.misc',
              'Lib.site-packages.fontTools.misc.plistlib', 'Lib.site-packages.fontTools.pens',
              'Lib.site-packages.fontTools.cu2qu', 'Lib.site-packages.fontTools.merge',
              'Lib.site-packages.fontTools.t1Lib', 'Lib.site-packages.fontTools.ttLib',
              'Lib.site-packages.fontTools.ttLib.tables', 'Lib.site-packages.fontTools.cffLib',
              'Lib.site-packages.fontTools.config', 'Lib.site-packages.fontTools.feaLib',
              'Lib.site-packages.fontTools.mtiLib', 'Lib.site-packages.fontTools.otlLib',
              'Lib.site-packages.fontTools.otlLib.optimize', 'Lib.site-packages.fontTools.subset',
              'Lib.site-packages.fontTools.svgLib', 'Lib.site-packages.fontTools.svgLib.path',
              'Lib.site-packages.fontTools.ufoLib', 'Lib.site-packages.fontTools.varLib',
              'Lib.site-packages.fontTools.varLib.instancer', 'Lib.site-packages.fontTools.voltLib',
              'Lib.site-packages.fontTools.colorLib', 'Lib.site-packages.fontTools.encodings',
              'Lib.site-packages.fontTools.unicodedata', 'Lib.site-packages.fontTools.designspaceLib',
              'Lib.site-packages.packaging', 'Lib.site-packages.pyparsing', 'Lib.site-packages.pyparsing.diagram',
              'Lib.site-packages.kiwisolver', 'Lib.site-packages.matplotlib', 'Lib.site-packages.matplotlib.tri',
              'Lib.site-packages.matplotlib._api', 'Lib.site-packages.matplotlib.axes',
              'Lib.site-packages.matplotlib.cbook', 'Lib.site-packages.matplotlib.style',
              'Lib.site-packages.matplotlib.tests', 'Lib.site-packages.matplotlib.testing',
              'Lib.site-packages.matplotlib.testing.jpl_units', 'Lib.site-packages.matplotlib.backends',
              'Lib.site-packages.matplotlib.backends.qt_editor', 'Lib.site-packages.matplotlib.sphinxext',
              'Lib.site-packages.matplotlib.projections', 'Lib.site-packages.setuptools',
              'Lib.site-packages.setuptools.extern', 'Lib.site-packages.setuptools._vendor',
              'Lib.site-packages.setuptools._vendor.packaging', 'Lib.site-packages.setuptools._vendor.more_itertools',
              'Lib.site-packages.setuptools.command', 'Lib.site-packages.setuptools._distutils',
              'Lib.site-packages.setuptools._distutils.command', 'Lib.site-packages.pkg_resources',
              'Lib.site-packages.pkg_resources.extern', 'Lib.site-packages.pkg_resources._vendor',
              'Lib.site-packages.pkg_resources._vendor.packaging', 'Lib.site-packages._distutils_hack'],
    ext_modules=cythonize(['particle_c.pyx', 'fit_plane_c.pyx', 'swarm_c.pyx'], language_level=3),
    url='',
    license='',
    author='julia',
    author_email='',
    description='',
    zip_safe=False
)
